---
- name: Execute generators
  hosts: localhost
  gather_facts: no

  tasks:
  
#---------------------------------clients-deployment---------------------------------------------------------------------------------------
    - name: deploy
      shell: microk8s kubectl apply -f /home/edge/NDT-EDGE/Edge/rn-clients-deployment/clients-conf/ -n default
      async: 3600
      poll: 0

    - name: Wait for 10 seconds
      pause:
        seconds: 10

    - name: Wait until all pods are ready
      shell: |
        total=$(microk8s kubectl get pods -n default --no-headers 2>/dev/null | wc -l)
        ready=$(microk8s kubectl get pods -n default --no-headers 2>/dev/null | grep -cE '^[^ ]+\s+([0-9]+)/\1\s+Running')
        if [ "$total" -eq 0 ]; then
          echo 1  # No pods yet
        elif [ "$total" -eq "$ready" ]; then
          echo 0  # All pods are Ready
        else
          echo 1  # Still waiting for pods to be Ready
        fi
      register: all_pods_ready
      until: all_pods_ready.stdout == "0"
      retries: 120
      delay: 10

#---------------------------------clients-config---------------------------------------------------------------------------------------

    - name: Configure resolv.conf in clients 1 to 7
      shell: microk8s kubectl exec -n default client{{ item }} -- /bin/bash -c 'echo -e "nameserver 8.8.8.8\noptions edns0" > /etc/resolv.conf'
      loop: "{{ range(1, 8) | list }}"
      ignore_errors: yes

#---------------------------------Tasks execution---------------------------------------------------------------------------------------
    - name: Execute ACROSSrandom_walk
      shell: microk8s kubectl exec -n default client1 -- python3.7 ACROSSrandom_walk.py 660
      async: 3600
      poll: 0
      register: random_result1

    - name: Execute file_transfer_wget
      shell: microk8s kubectl exec -n default client2 -- timeout 660 python3 ACROSSfile_transfer.py https://ia800301.us.archive.org/21/items/ThePhantomoftheOpera/Phantom_of_the_Opera_512kb.mp4 400K
      async: 3600
      poll: 0

    - name: Execute ACROSSconsuming_video_YT.py
      shell: microk8s kubectl exec -n default client3 -- python3.7 ACROSSconsuming_video_YT.py https://www.youtube.com/watch?v=wnhvanMdx4s 660 #set time and url
      async: 3600
      poll: 0
      register: youtube_result1

    - name: Execute file_transfer wget
      shell: microk8s kubectl exec -n default client4 -- timeout 660 python3 ACROSSfile_transfer.py https://planet.openstreetmap.org/planet/planet-latest.osm.bz2 14M
      async: 3600
      poll: 0

    - name: Execute ACROSSconsuming_video.py
      shell: microk8s kubectl exec -n default client5 -- python3.7 ACROSSconsuming_video.py https://www.twitch.tv/leekbeats 660 #set time and url
      async: 3600
      poll: 0
      register: twitch_result1

    - name: Execute shorts
      shell: microk8s kubectl exec -n default client6 -- python3.7 ACROSSshorts.py 660
      async: 3600
      poll: 0
      register: shorts_result1

    - name: Execute ACROSSconsuming_video.py
      shell: microk8s kubectl exec -n default client7 -- python3.7 ACROSSconsuming_video.py https://www.twitch.tv/videos/2480518040 660 #set time and url
      async: 3600
      poll: 0
      register: twitch_result2

    # Waiting tasks
    - name: Waiting
      async_status:
        jid: "{{ item.ansible_job_id }}"
      loop:
        - "{{ youtube_result1 }}"
        - "{{ twitch_result1 }}"
        - "{{ twitch_result2 }}"
        - "{{ shorts_result1 }}"
        - "{{ random_result1 }}"
      register: acrossclient_jobs
      until: acrossclient_jobs.finished
      retries: 999
      delay: 15
      ignore_errors: yes

#---------------------------------Clients-deployment delete---------------------------------------------------------------------------------------
    - name: deploy
      shell: microk8s kubectl delete -f /home/edge/NDT-EDGE/Edge/rn-clients-deployment/clients-conf/ -n default
      async: 3600
      poll: 0
 