#cloud-config
hostname: edge-3
fqdn: edge-3
manage_etc_hosts: True
users:
  - name: edge                       
    password: "ubuntu-edge3"
    sudo: ALL=(ALL) NOPASSWD:ALL  
chpasswd: { expire: False }
ssh_pwauth: True
timezone: Europe/Madrid

runcmd:
  - apt-get update
  - apt-get install -y docker.io
  - systemctl enable docker
  - systemctl start docker
