---
- name: Topology Configuration
  hosts: localhost
  gather_facts: no
  vars:
    cgclients: []
    ddosclients: []
    limit_cg: 25
    limit_ddos: 21
    
  tasks:
#------------------------------------------Ip_routes---------------------------------------------------------------------      

    - name: Configure cgserver
      shell: kubectl exec -it -n ddos cgserver -- python3 cgserver-config.py
      
    - name: Configure ddosserver
      shell: kubectl exec -it -n ddos ddosserver -- python3 ddosserver-config.py

    - name: Configure gateway2
      shell: kubectl exec -n ddos gateway2 -- python3 gateway2-config.py

    - name: Configure gateway1
      shell: kubectl exec -n ddos gateway1 -- python3 gateway1-config.py


    - name: Get cgserver IP
      shell: "kubectl exec -n ddos cgserver -- ip addr show eth1 | awk '/inet / {gsub(/\\/\\/[0-9]+/, \"\", $2); print $2}'"
      register: cgserver_ip_output
      changed_when: false
      ignore_errors: yes

    - name: Extract IP from cgserver_ip_output
      set_fact:
        cgserver_ip: "{{ cgserver_ip_output.stdout.split('/')[0] }}"
        
    - name: Debug cgserverip
      debug:
        var: cgserver_ip

    - name: Get ddosserver IP
      shell: "kubectl exec -n ddos ddosserver -- ip addr show eth1 | awk '/inet / {gsub(/\\/\\/[0-9]+/, \"\", $2); print $2}'"
      register: ddosserver_ip_output
      changed_when: false
      ignore_errors: yes

    - name: Extract IP from ddosserver_ip_output
      set_fact:
        ddosserver_ip: "{{ ddosserver_ip_output.stdout.split('/')[0] }}"
        
    - name: Debug ddosserverip
      debug:
        var: ddosserver_ip   
        
        
    - name: Store server IPs in a file
      copy:
        content: |
          ddosserver_ip: "{{ ddosserver_ip }}"
          cgserver_ip: "{{ cgserver_ip }}"
        dest: "{{ playbook_dir }}/server_ips.yaml"

  #---------------------------------------internet pod configuration----------------------------------------------------------------------------------------------
      
    - name: Iptables
      shell: kubectl exec -n ddos gateway2 -- /bin/sh -c 'iptables -t nat -A POSTROUTING -o eth2 -j MASQUERADE'
      ignore_errors: yes

 #---------------------------------------configure micaddy.com ip----------------------------------------------------------------------------------------------   

    - name: Update micaddy.com IP
      shell:  kubectl exec -n ddos ddosserver -- env ddosserver={{ ddosserver_ip }}  /bin/bash -c '/bin/sed -i "s/172\\.21\\.0\\.6/$ddosserver/g" /etc/bind/zones/db.micaddy.com'
      ignore_errors: yes

#---------------------------------------debug routers----------------------------------------------------------------------------------------------

    - name: Debug internet connection
      shell: kubectl exec -n ddos ceos2 -- /bin/bash -c 'until ping -c 1 -i 20 8.8.8.8; do :; done; exit 0'
      ignore_errors: yes

#---------------------------------------tcpdump----------------------------------------------------------------------------------------------

    # - name: Start dumps
    #   shell: kubectl exec -n ddos {{ item.pod }} -- tcpdump -i {{ item.interface }} -w /home/{{ item.pod }}_{{ item.interface }}.pcap
    #   loop:
    #     - { pod: "ceos11", interface: "eth4" }
    #     - { pod: "ceos11", interface: "eth1" }
    #     - { pod: "ceos11", interface: "eth2" }
    #     - { pod: "ceos11", interface: "eth3" }
    #     - { pod: "ceos11", interface: "eth5" }
    #     - { pod: "ceos11", interface: "eth6" }
    #     - { pod: "ceos11", interface: "eth7" }
    #     - { pod: "ceos11", interface: "eth8" }
    #     - { pod: "ceos11", interface: "eth9" }
    #     - { pod: "ceos11", interface: "eth10" }
    #     - { pod: "ceos11", interface: "eth11" }
    #     - { pod: "ceos11", interface: "eth12" }
    #     - { pod: "ceos11", interface: "eth13" }
    #     - { pod: "ceos11", interface: "eth14" }
    #     - { pod: "ceos11", interface: "eth15" }
    #     - { pod: "ceos11", interface: "eth16" }
    #     - { pod: "ceos11", interface: "eth17" }
    #     - { pod: "ceos11", interface: "eth18" }
    #     - { pod: "ceos11", interface: "eth19" }
    #     - { pod: "ceos11", interface: "eth20" }
    #     - { pod: "ceos11", interface: "eth21" }
    #     - { pod: "ceos11", interface: "eth22" }
    #     - { pod: "ceos11", interface: "eth23" }
    #     - { pod: "ceos13", interface: "eth1" }
    #     - { pod: "ceos13", interface: "eth2" }
    #     - { pod: "ceos13", interface: "eth3" }
    #     - { pod: "ceos13", interface: "eth4" }
    #     - { pod: "ceos13", interface: "eth5" }
    #     - { pod: "ceos13", interface: "eth6" }
    #     - { pod: "ceos13", interface: "eth7" }
    #     - { pod: "ceos13", interface: "eth8" }
    #     - { pod: "ceos13", interface: "eth9" }
    #     - { pod: "ceos13", interface: "eth10" }
    #     - { pod: "ceos13", interface: "eth11" }
    #     - { pod: "ceos1", interface: "eth2" }
    #     - { pod: "ceos1", interface: "eth3" }
    #     - { pod: "ceos1", interface: "eth4" }
    #     - { pod: "ceos1", interface: "eth5" }
    #     - { pod: "ceos2", interface: "eth1" }
    #     - { pod: "ceos2", interface: "eth2" }
    #     - { pod: "ceos2", interface: "eth3" }
    #     - { pod: "ceos2", interface: "eth4" }
    #     - { pod: "ceos2", interface: "eth5" }
    #     - { pod: "ceos3", interface: "eth1" }
    #     - { pod: "ceos3", interface: "eth2" }
    #     - { pod: "ceos3", interface: "eth3" }
    #     - { pod: "ceos3", interface: "eth4" }
    #     - { pod: "ceos3", interface: "eth5" }
    #     - { pod: "ceos4", interface: "eth2" }
    #     - { pod: "ceos4", interface: "eth3" }
    #     - { pod: "ceos4", interface: "eth4" }
    #     - { pod: "ceos6", interface: "eth2" }
    #     - { pod: "ceos6", interface: "eth3" }
    #     - { pod: "ceos6", interface: "eth4" }
    #     - { pod: "ceos5", interface: "eth2" }
    #     - { pod: "ceos5", interface: "eth3" }
    #     - { pod: "ceos7", interface: "eth2" }
    #     - { pod: "ceos7", interface: "eth3" }
    #     - { pod: "ceos7", interface: "eth4" }
    #     - { pod: "ceos12", interface: "eth2" }
    #     - { pod: "ceos12", interface: "eth4" }
    #   async: 3600
    #   poll: 0


#---------------------------------------ddosclient, cgserver and ddosserver configuration----------------------------------------------------------------------------------------------

    - name: Start ACROSSserver.py
      shell: kubectl exec -n ddos cgserver -- python3 ACROSSserver.py &
    
    - name: Start ssh
      shell: kubectl exec -n ddos cgserver -- /usr/sbin/sshd -D &

    - name: Start bind9
      shell: kubectl exec -n ddos ddosserver -- service named start

    - name: Start caddy
      shell: kubectl exec -n ddos ddosserver -- caddy run --config /etc/caddy/Caddyfile &

    - name: Start dnsdist
      shell: kubectl exec -n ddos ddosserver -- service dnsdist start

    # - name: Start dnscrypt
    #   shell: kubectl exec -n ddos {{ item.pod }} -- ./dnscrypt-proxy-linux_x86_64-2.1.5/config.sh
    #   loop: "{{ ddosclients }}" 
