---
- name: Replay pcap
  hosts: localhost
  gather_facts: no
    
  tasks:
#------------------------------------------Ip_routes---------------------------------------------------------------------      
      
    - name: Replay
      shell: kubectl exec -it -n 6gndt r2 -- tcpreplay -i ens6 /home/r2/ens6_r2.pcap