#cloud-config
hostname: r4
fqdn: r4
manage_etc_hosts: True

users:
  - name: r4
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: sudo

chpasswd:
  list: |
    r4:r4-frr
  expire: false
  encrypted: false

ssh_pwauth: True
timezone: Europe/Madrid

package_update: true
package_upgrade: true

runcmd:
  - git clone https://github.com/Mouseworld-Lab/NDT-EDGE.git /opt/realnetwork
  - cp /opt/realnetwork/config/${hostname}.conf /etc/frr/frr.conf