#cloud-config
hostname: r11
fqdn: r11
manage_etc_hosts: True

users:
  - name: r11
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: sudo

chpasswd:
  list: |
    r11:r11-frr
  expire: false
  encrypted: false

ssh_pwauth: True
timezone: Europe/Madrid

package_update: true
package_upgrade: true

runcmd:
  - sudo git clone https://github.com/Mouseworld-Lab/NDT-EDGE.git /home/r11/NDT-EDGE
  - sudo cp /home/r11/NDT-EDGE/realnetwork/config/r11.conf /etc/frr/frr.conf
  - sudo chown frr:frr /etc/frr/frr.conf
  - sudo rm -rf /home/r11/NDT-EDGE
  - sudo /usr/lib/frr/frrinit.sh restart
  - sudo ip link add veth0 type veth peer name veth1
  - sudo ip link set veth0 up
  - sudo ip link set veth1 up

  - sudo apt-get install bridge-utils
  - sudo brctl addbr br0
  - sudo brctl addif br0 veth0
  - sudo ip link set br0 up

  - sudo ip add add 10.0.1.20/24 dev veth1
  - sudo ip route add 10.0.2.0/24 via 10.0.1.15 dev veth1
###
  - sudo ip route del default 
  - sudo ip route add default via 192.168.1.1 dev ens4

  - sudo apt-get update
  - sudo apt-get install -y traceroute

##
  - sudo ip link add vxlan-1 type vxlan id 96 dev ens3 dstport 47 remote  192.168.27.185
  - sudo ip link set vxlan-1 up
  - sudo brctl addif br0 vxlan-1

