#cloud-config
hostname: r1
fqdn: r1
manage_etc_hosts: True

users:
  - name: r1
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: sudo

chpasswd:
  list: |
    r1:r1-frr
  expire: false
  encrypted: false

ssh_pwauth: True
timezone: Europe/Madrid

package_update: true
package_upgrade: true

runcmd:
runcmd:
  - sudo git clone https://github.com/Mouseworld-Lab/NDT-EDGE.git /tmp/NDT-EDGE
  - sudo cp /tmp/NDT-EDGE/realnetwork/config/r1.conf /etc/frr/frr.conf
  - sudo chown frr:frr /etc/frr/frr.conf
  - sudo rm -rf /tmp/NDT-EDGE
  - sudo /usr/lib/frr/frrinit.sh restart
  - sudo ip route del default 
  - sudo ip route add default via 192.168.4.20 dev ens5
  - sudo ip route add 10.0.2.0/24 via 192.168.1.11 dev ens6
  - sudo apt-get update
  - sudo apt-get install -y traceroute