#cloud-config
hostname: r6
fqdn: r6
manage_etc_hosts: True

users:
  - name: r6
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: sudo

chpasswd:
  list: |
    r6:r6-frr
  expire: false
  encrypted: false

ssh_pwauth: True
timezone: Europe/Madrid

package_update: true
package_upgrade: true

runcmd:
  - sudo git clone https://github.com/Mouseworld-Lab/NDT-EDGE.git /home/r6/NDT-EDGE
  - sudo cp /home/r6/NDT-EDGE/realnetwork/config/r6.conf /etc/frr/frr.conf
  - sudo chown frr:frr /etc/frr/frr.conf
  - sudo rm -rf /home/r6/NDT-EDGE
  - sudo /usr/lib/frr/frrinit.sh restart
  - sudo ip route del default 
  - sudo ip route add default via 192.168.7.5 dev ens5
  - sudo ip route add 10.0.2.0/24 via 192.168.5.4 dev ens6
  - sudo apt-get update
  - sudo apt-get install -y traceroute