#cloud-config
hostname: r6
fqdn: r6
manage_etc_hosts: True

users:
  - name: r6
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: sudo

chpasswd:
  list: |
    r6:r6-frr
  expire: false
  encrypted: false

ssh_pwauth: True
timezone: Europe/Madrid

package_update: true
package_upgrade: true

runcmd:
  - git clone https://github.com/Mouseworld-Lab/NDT-EDGE.git /opt/realnetwork
  - cp /opt/realnetwork/config/${hostname}.conf /etc/frr/frr.conf
  