#cloud-config
hostname: r12
fqdn: r12
manage_etc_hosts: True

users:
  - name: r12
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: sudo

chpasswd:
  list: |
    r12:r12-frr
  expire: false
  encrypted: false

ssh_pwauth: True
timezone: Europe/Madrid

package_update: true
package_upgrade: true

runcmd:
  - sudo git clone https://github.com/Mouseworld-Lab/NDT-EDGE.git /home/r12/NDT-EDGE
  - sudo cp /home/r12/NDT-EDGE/realnetwork/config/r12.conf /etc/frr/frr.conf
  - sudo chown frr:frr /etc/frr/frr.conf
  - sudo rm -rf /home/r12/NDT-EDGE
  - sudo /usr/lib/frr/frrinit.sh restart