#cloud-config
hostname: r7
fqdn: r7
manage_etc_hosts: True

users:
  - name: r7
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: sudo

chpasswd:
  list: |
    r7:r7-frr
  expire: false
  encrypted: false

ssh_pwauth: True
timezone: Europe/Madrid

package_update: true
package_upgrade: true

runcmd:
  - sudo git clone https://github.com/Mouseworld-Lab/NDT-EDGE.git /home/r7/NDT-EDGE
  - sudo cp /home/r7/NDT-EDGE/realnetwork/config/r7.conf /etc/frr/frr.conf
  - sudo chown frr:frr /etc/frr/frr.conf
  - sudo rm -rf /home/r7/NDT-EDGE
  - sudo /usr/lib/frr/frrinit.sh restart
  - sudo ip route del default 
  - sudo ip route add default via 192.168.10.3 dev ens6
  - sudo ip route add 10.0.2.0/24 via 192.168.9.6 dev ens4
  - sudo apt-get update
  - sudo apt-get install -y traceroute